# Generated by Django 4.1.1 on 2025-01-04 02:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('rango_desde', models.PositiveSmallIntegerField(help_text='Debe ser un número entre 0 y 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rango_hasta', models.PositiveSmallIntegerField(help_text='Debe ser un número entre 0 y 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('categoria', models.CharField(max_length=100)),
                ('duracion', models.DurationField()),
                ('descripcion', models.TextField()),
                ('horario', models.CharField(max_length=255)),
            ],
        ),
    ]
