# Generated by Django 4.2.17 on 2025-01-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='images/original/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='images/procesada/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
