# Generated by Django 4.1.1 on 2025-01-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=255)),
                ('medio_dia', models.CharField(max_length=255)),
                ('noche', models.CharField(max_length=255)),
            ],
        ),
    ]
